## Virtual environments:
- **conda create -n <venv_name>** — create a new conda environment.
- **conda activate <venv_name>** — activate (use) the environment.
- **conda deactivate** — deactivate the environment.

In [9]:
import numpy as np

# Casting as a numpy array
A = np.array([1,2,3,4])

print('dtype:', A.dtype) # Type of what is stored in the array ! NOT PYTHON TYPES !

print('ndim:', A.ndim) # Number of dimensions (axes in numpy speak)

print('shape:', A.shape) # size of the dimensions are expressed a tuple

print('reshape to (4,1):', A.reshape((4,1)).shape) # a column vector (Transposed ?)

# Two dimensional arrays have a 2-tuple shape

a = np.array([1,2,3,4,5,6,7,8,9])
print('a:', a, '\n')
b = a.reshape((3,3)) # creates a 3x3 numpy array from the 1x9 array
print('b:\n', b, '\n')

print('b * 10 + 4:\n', b * 10 + 4)


dtype: int32
ndim: 1
shape: (4,)
reshape to (4,1): (4, 1)
a: [1 2 3 4 5 6 7 8 9] 

b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

b * 10 + 4:
 [[14 24 34]
 [44 54 64]
 [74 84 94]]


### Here are a few of the most important attributes of dtype objects:
- **dtype.byteorder** — big or little endian
- **dtype.itemsize** — element size of this dtype
- **dtype.name** — a name for this dtype object
- **dtype.type** — type object used to create scalars


In [10]:
#Forcing a data type:
a = np.array([1,2,3], dtype=np.float32)

# Primitives ti create np arrays:
print('arange:\n', np.arange(10), '\n') #creates numpy array of len 10 with values 0-9

print('linspace:\n', np.linspace(0, 1, 5), '\n') # creates numpy array of len 5 with values 0-1

print('zeros:\n', np.zeros((2, 2)), '\n') # creates a 2x2 array of zeros

print('ones:\n', np.ones((1, 5)), '\n') # creates a 1x5 array of ones

print('empty:\n', np.empty((1, 3)), '\n') # creates a 1x3 array of uninitialized values

print('eye:\n', np.eye(3), '\n') # creates a 3x3 identity matrix (diagonal is 1)

print('diag:\n', np.diag(np.array([1, 2, 3, 4])), '\n') # creates a 4x4 matrix with the given values on the diagonal


arange:
 [0 1 2 3 4 5 6 7 8 9] 

linspace:
 [0.   0.25 0.5  0.75 1.  ] 

zeros:
 [[0. 0.]
 [0. 0.]] 

ones:
 [[1. 1. 1. 1. 1.]] 

empty:
 [[1. 1. 1.]] 

eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

diag:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]] 



![img](images/img1.png)

In [17]:
arr = np.arange(15).reshape((3, 5))
print('arr:\n', arr, '\n')

print('Selecting the last row except the first column:', arr[2, 1:], '\n')

arr:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

Selecting the last row except the first column: [11 12 13 14] 



![img2](images/img2.png)

- Simple assigments do not make copies of arrays (same semantics as Python)
- Slicing operations do not make copies either; they return views on the original array

#### NumPy ***ufuncs*** are functions that operate element-wise on one or more arrays:
- **comparison**: <, <=, ==, !=, >=, >
- **arithmetic**: +, -, *, /, reciprocal, square
- **exponential**: exp, expm1, exp2, log, log10, log1p, log2, power, sqrt
- **trigonometric**: sin, cos, tan, acsin, arccos, atctan
- **hyperbolic**: sinh, cosh, tanh, acsinh, arccosh, atctanh
- **bitwise operations**: &, |, ~, ^, left_shift, right_shift
- **logical operations**: and, logical_xor, not, or
- **predicates**: isfinite, isinf, isnan, signbit
- **other**: abs, ceil, floor, mod, modf, round, sinc, sign, trunc


#### Reduction operation lets you lose one or more dimension
- **np.sum()** — sum of all elements

Array method reductions take an optional **axis parameter** that specifies over which axes
to reduce (*axis*=None reduces into a single scalar). 
<u>The axis is the index of the dimension i want to lose</u>:

![img3](images/img3.png)
![img4](images/img4.png)

#### Broadcasting: 
numpy figures out how to do operations on arrays of different shapes

In [21]:
#Broadcasting example:
a = np.arange(4).reshape((4,1))
print('a:\n', a, '\n')
b = np.arange(5).reshape((1,5))
print('b:\n', b, '\n')

print('a + b:\n', a + b, '\n') # a is broadcasted to match the shape of b
#numpy repeats the array to match the shape of the other array

#adds a 1 to the left and from the right 
# indexes checks if the dimensions are integer dividable

a:
 [[0]
 [1]
 [2]
 [3]] 

b:
 [[0 1 2 3 4]] 

a + b:
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]] 



In [24]:
# For the broadcasting I can also use 
a = np.arange(6).reshape((2, 3))
print('a:\n', a, '\n')

b = np.array([10, 100])
print('b:\n', b, '\n')

print('a * b[:,np.newaxis]:\n', a * b[:,np.newaxis]) # (2, 3) * (2, 1): Adds a 1 in a particular dimension

a:
 [[0 1 2]
 [3 4 5]] 

b:
 [ 10 100] 

a * b[:,np.newaxis]:
 [[  0  10  20]
 [300 400 500]]


Array Methods:
- **Predicates**: a.any(), a.all()
- **Reductions**: a.mean(), a.argmin(), a.argmax(),a.trace(),
    a.cumsum(), a.cumprod()
- **Manipulation**: a.argsort(), a.transpose(), a.reshape(...),
    a.ravel(), a.fill(...), a.clip(...)
- **Complex Numbers**: a.real, a.imag, a.conj()


In [32]:
# argmin gives the element with the lowest value

a = np.random.randint(2, size=(10,5))
print('a:\n', a, '\n')
print('a.argmin:', a.argmin(), '\n') # gives the index of the lowest value

print('Number of 1 in the second column: ', (a[:,1]==1).sum()) # counts the number of 1s in the second column

a:
 [[1 1 0 1 1]
 [0 1 1 1 1]
 [1 0 1 0 1]
 [0 0 1 1 1]
 [1 1 0 1 0]
 [0 1 1 1 0]
 [1 0 0 1 0]
 [1 1 1 1 0]
 [0 1 0 0 1]
 [0 0 1 0 0]] 

a.argmin:
 2 

Number of 1 in the second column:  6


### Transpose operation:

In [39]:
a = np.arange(6).reshape((2, 3))
print('a:\n', a, '\n')

print('a.transpose:\n', a.transpose(), '\n')

# In case 'a' has more than 2 dim:
a = np.arange(24).reshape((2, 3, 4))

# The first dim becomes the second, 
# the second becomes the third and the third becomes the first
a.transpose((1, 2, 0)) 
print('a.transpose((1, 2, 0)):\n', a.transpose((1, 2, 0)), '\n')

# !! NEVER TRUST RESHAPE FOR TRANSPOSITIONS !!

a:
 [[0 1 2]
 [3 4 5]] 

a.transpose:
 [[0 3]
 [1 4]
 [2 5]] 

a.transpose((1, 2, 0)):
 [[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]] 



In [41]:
a = np.arange(15).reshape((3, 5))
print('a:\n', a, '\n')

b = (a % 3 == 0) # creates a boolean array for the condition
print('b:\n', b, '\n')

# selects the elements in which the condition is true
print('Where is the condition true in a?\n', a[b]) 


a:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

b:
 [[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]] 

Where is the condition true in a?
 [ 0  3  6  9 12]


## NumPy Functions
- **Data I/O**: fromfile, genfromtxt, load, loadtxt, save, savetxt
- **Mesh Creation**: mgrid, meshgrid, ogrid
- **Manipulation**: einsum, hstack, take, vstack
## Other Subpackages:
- **numpy.fft** — Fast Fourier transforms
- **numpy.polynomial** — Efficient polynomials
- **numpy.linalg** — Linear algebra cholesky, det, eig, eigvals, inv, lstsq, norm, qr, svd
- **numpy.math**: — C standard library math functions
- **numpy.random** — Random number generation beta, gamma, geometric, hypergeometric, lognormal, normal, poisson, uniform, weibull
